#!/bin/sh

# Count
count=100

# Dict installed ?
if [ ! -e /usr/local/share/mozilla-dicts/en-GB.dic ]; then echo "\nplease: doas pkg_add mozilla-dicts-en-GB\n"; exit 1; fi
if [ ! -e /usr/local/share/mozilla-dicts/de-CH.dic ]; then echo "\nplease: doas pkg_add mozilla-dicts-de-CH\n"; exit 1; fi
if [ ! -e /usr/local/share/mozilla-dicts/es-ES.dic ]; then echo "\nplease: doas pkg_add mozilla-dicts-es-es\n"; exit 1; fi
if [ ! -e /usr/local/share/mozilla-dicts/fr-xx-classique.dic ]; then echo "\nplease: doas pkg_add mozilla-dicts-fr\n"; exit 1; fi

# Go
data=$(cat /usr/local/share/mozilla-dicts/*.dic |\
        egrep -v "'" |\
        egrep -v "\." |\
        egrep -v "\?" |\
        sed 's/\/.*//' |\
        tr -dc [:graph:][:cntrl:] |\
        egrep "^.{4}$" |\
	egrep -i "^$1" |\
        sort |\
        uniq |\
        sort -R |\
        head -$count)

echo
print "$data" |paste - - - - - - - - - -
echo

exit 0
