#!/bin/sh

# Count
count=100

# Dict installed ?
if 	[ ! -e /usr/local/share/mozilla-dicts/en-GB.dic ] || \
	[ ! -e /usr/local/share/mozilla-dicts/de-CH.dic ] || \
	[ ! -e /usr/local/share/mozilla-dicts/es-ES.dic ] || \
	[ ! -e /usr/local/share/mozilla-dicts/fr-xx-classique.dic ]; then
	
		doas pkg_add mozilla-dicts-en-GB
		doas pkg_add mozilla-dicts-de-CH
		doas pkg_add mozilla-dicts-es-es
		doas pkg_add mozilla-dicts-fr

fi

# Go
data=$(cat /usr/local/share/mozilla-dicts/*.dic |\
        egrep -v "'" |\
        egrep -v "\." |\
        egrep -v "\?" |\
        sed 's/\/.*//' |\
        tr -dc [:graph:][:cntrl:] |\
        egrep "^.{4}$" |\
	egrep -i "^$1" |\
        sort |\
        uniq |\
        sort -R |\
        head -$count)

echo
print "$data" |paste - - - - - - - - - -
echo

exit 0
